/**
 * Goal and activity calculation concept taken from
 * https://www.musclehacking.com/calorie-calculator/#activity-level
 * */
const ACTIVITYFACTORS = {
  // Multiplies the BMR by 1.2
  sedentary: 1.2,
  // Multiplies the BMR by 1.375
  lightlyActive: 1.375,
  // Multiplies the BMR by 1.55
  moderatelyActive: 1.55,
  // Multiplies the BMR by 1.725
  veryActive: 1.725,
  // Multiplies the BMR by 1.9
  extremelyActive: 1.9,
};

/**
 * Goal and activity calculation concept taken from
 * https://www.musclehacking.com/calorie-calculator/#activity-level
 * */
const GOALFACTORS = {
  // Reduce daily calories by 20% to lose weight
  loseWeight: 0.8,
  // Reduce daily calories by 10% to slowly lose weight
  slowlyLoseWeight: 0.9,
  // Maintain current weight
  maintainWeight: 1.0,
  // Increase daily calories by 10% to slowly gain weight
  slowlyGainWeight: 1.1,
  // Increase daily calories by 20% to gain weight
  gainWeight: 1.2,
};

// Thes constants were generated by the use of chatgtp
// Diet meals
const MEALS = {
  vegetarian: [
    { name: "Vegetarian Pizza", calories: 700 },
    { name: "Spinach and Feta Salad", calories: 400 },
    { name: "Vegetable Stir Fry", calories: 450 },
    { name: "Chickpea Curry", calories: 550 },
    { name: "Mushroom Risotto", calories: 600 },
    { name: "Pumpkin Soup", calories: 300 },
    { name: "Stuffed Bell Peppers", calories: 500 },
    { name: "Tomato Basil Pasta", calories: 550 },
    { name: "Cauliflower Tacos", calories: 480 },
    { name: "Veggie Burger", calories: 650 },
    { name: "Veggie Lasagna", calories: 650 },
    { name: "Garlic Parmesan Zucchini", calories: 450 },
    { name: "Creamy Mushroom Soup", calories: 400 },
    { name: "Sweet Corn Risotto", calories: 550 },
    { name: "Eggplant Parmesan", calories: 500 },
    { name: "Baked Ziti", calories: 470 },
    { name: "Carrot and Coriander Soup", calories: 350 },
    { name: "Butternut Squash Casserole", calories: 480 },
    { name: "Roasted Beet Salad", calories: 320 },
    { name: "Paneer Tikka Masala", calories: 550 },
    { name: "Greek Salad", calories: 380 },
    { name: "Ratatouille", calories: 420 },
    { name: "Quiche Lorraine", calories: 450 },
    { name: "Spinach Quiche", calories: 430 },
    { name: "Margherita Pizza", calories: 540 },
  ],
  vegan: [
    { name: "Vegan Burrito Bowl", calories: 650 },
    { name: "Tofu Stir Fry", calories: 500 },
    { name: "Lentil Soup", calories: 400 },
    { name: "Vegan Chili", calories: 450 },
    { name: "Sweet Potato Curry", calories: 550 },
    { name: "Quinoa and Black Bean Salad", calories: 410 },
    { name: "Vegan Pancakes", calories: 350 },
    { name: "Green Smoothie Bowl", calories: 330 },
    { name: "Avocado Sushi Rolls", calories: 470 },
    { name: "Falafel Wrap", calories: 520 },
    { name: "Vegan Tacos", calories: 460 },
    { name: "Vegan Jambalaya", calories: 480 },
    { name: "Vegan Paella", calories: 520 },
    { name: "Jackfruit BBQ Sandwich", calories: 530 },
    { name: "Seitan Stir-Fry", calories: 450 },
    { name: "Vegan Pho", calories: 380 },
    { name: "Vegan Ramen", calories: 420 },
    { name: "Moroccan Vegetable Tagine", calories: 440 },
    { name: "Vegan Shepherd's Pie", calories: 460 },
    { name: "Vegan Gumbo", calories: 480 },
    { name: "Mushroom Stroganoff", calories: 510 },
    { name: "Thai Green Curry", calories: 450 },
    { name: "Vegan Bolognese", calories: 530 },
    { name: "Vegan Enchiladas", calories: 540 },
    { name: "Portobello Fajitas", calories: 460 },
  ],
  pescatarian: [
    { name: "Grilled Salmon", calories: 500 },
    { name: "Shrimp Paella", calories: 450 },
    { name: "Fish Tacos", calories: 480 },
    { name: "Seared Tuna Salad", calories: 410 },
    { name: "Crab Cakes", calories: 530 },
    { name: "Clam Chowder", calories: 550 },
    { name: "Mussels in White Wine Sauce", calories: 510 },
    { name: "Grilled Scallops", calories: 320 },
    { name: "Salmon Sushi", calories: 350 },
    { name: "Fish and Chips", calories: 700 },
    { name: "Baked Cod with Lemon", calories: 400 },
    { name: "Tuna Nicoise Salad", calories: 450 },
    { name: "Grilled Mahi Mahi", calories: 480 },
    { name: "Cajun Shrimp Skillet", calories: 520 },
    { name: "Anchovy Pasta", calories: 510 },
    { name: "Oyster Stew", calories: 450 },
    { name: "Lobster Thermidor", calories: 580 },
    { name: "Poached Haddock", calories: 420 },
    { name: "Seafood Risotto", calories: 470 },
    { name: "Sardine Toast", calories: 400 },
    { name: "Smoked Salmon Bagel", calories: 380 },
    { name: "Grilled Octopus", calories: 360 },
    { name: "Fish Pie", calories: 550 },
    { name: "Scallop Ceviche", calories: 320 },
    { name: "Halibut Steaks", calories: 490 },
  ],
  glutenFree: [
    { name: "Gluten-free Pasta", calories: 500 },
    { name: "Quinoa Salad", calories: 350 },
    { name: "Rice and Bean Bowl", calories: 420 },
    { name: "Chicken and Broccoli Stir Fry", calories: 480 },
    { name: "Stuffed Turkey Peppers", calories: 510 },
    { name: "Gluten-free Pancakes", calories: 400 },
    { name: "Butternut Squash Soup", calories: 300 },
    { name: "Gluten-free Pizza", calories: 550 },
    { name: "Beef Stir Fry", calories: 450 },
    { name: "Almond Flour Waffles", calories: 330 },
    { name: "Baked Salmon with Dill", calories: 510 },
    { name: "Stuffed Acorn Squash", calories: 460 },
    { name: "Gluten-Free Fettuccine Alfredo", calories: 520 },
    { name: "Gluten-Free Tiramisu", calories: 420 },
    { name: "Cauliflower Fried Rice", calories: 380 },
    { name: "Roast Beef", calories: 540 },
    { name: "Lamb Kofta", calories: 530 },
    { name: "Gluten-Free Fish Sticks", calories: 470 },
    { name: "Sweet Potato Noodles", calories: 350 },
    { name: "Moroccan Chicken", calories: 500 },
    { name: "Pork Tenderloin with Apples", calories: 480 },
    { name: "Gluten-Free Beef Stroganoff", calories: 520 },
    { name: "Turkey Chili", calories: 460 },
    { name: "Gluten-Free Gyros", calories: 450 },
    { name: "Roasted Duck with Plum Sauce", calories: 550 },
  ],
  dairyFree: [
    { name: "Dairy-free Smoothie", calories: 300 },
    { name: "Avocado Toast", calories: 400 },
    { name: "Coconut Yogurt Parfait", calories: 350 },
    { name: "Lentil and Veggie Stew", calories: 500 },
    { name: "Chicken Tikka Masala", calories: 450 },
    { name: "Beef and Broccoli", calories: 500 },
    { name: "Pea Soup", calories: 320 },
    { name: "Roasted Vegetable Bowl", calories: 550 },
    { name: "Turkey Lettuce Wraps", calories: 400 },
    { name: "Shrimp and Avocado Salad", calories: 450 },
    { name: "Dairy-Free Mac and Cheese", calories: 520 },
    { name: "Spicy Bean Chili", calories: 460 },
    { name: "Pulled Jackfruit Sliders", calories: 430 },
    { name: "Beef Stew", calories: 480 },
    { name: "Roasted Lamb with Vegetables", calories: 520 },
    { name: "Dairy-Free Fudge", calories: 400 },
    { name: "Vegan Sausage Roll", calories: 420 },
    { name: "Banana Coconut Muffins", calories: 310 },
    { name: "Spiced Pumpkin Pie", calories: 360 },
    { name: "Eggplant and Bean Casserole", calories: 490 },
    { name: "Moroccan Lamb Tagine", calories: 510 },
    { name: "BBQ Chicken Drumsticks", calories: 450 },
    { name: "Tofu Scramble", calories: 350 },
    { name: "Spaghetti Squash with Tomato Sauce", calories: 380 },
    { name: "Vegan Banana Bread", calories: 400 },
  ],
  keto: [
    { name: "Keto Bacon and Eggs", calories: 400 },
    { name: "Keto Avocado Burger", calories: 450 },
    { name: "Keto Steak Salad", calories: 480 },
    { name: "Keto Chicken Wings", calories: 520 },
    { name: "Cheese and Herb Omelet", calories: 300 },
    { name: "Pork Rinds", calories: 320 },
    { name: "Keto Buffalo Chicken Dip", calories: 450 },
    { name: "Keto Zucchini Bread", calories: 360 },
    { name: "Keto Fish Cakes", calories: 410 },
    { name: "Keto Turkey Meatballs", calories: 390 },
    { name: "Keto Garlic Bread", calories: 340 },
    { name: "Stuffed Avocados", calories: 320 },
    { name: "Keto Chocolate Cake", calories: 410 },
    { name: "Keto Eggplant Parmesan", calories: 450 },
    { name: "Keto Mushroom Caps", calories: 300 },
    { name: "Keto Cauliflower Hash Browns", calories: 350 },
    { name: "Keto Cobb Salad", calories: 490 },
    { name: "Keto Pulled Pork", calories: 480 },
    { name: "Keto Egg Roll in a Bowl", calories: 430 },
    { name: "Keto Cucumber Sandwiches", calories: 310 },
    { name: "Keto Meatloaf", calories: 500 },
    { name: "Keto Pecan Pie", calories: 470 },
    { name: "Keto Sausage and Peppers", calories: 510 },
    { name: "Keto Jalapeno Poppers", calories: 360 },
    { name: "Keto Spinach Artichoke Dip", calories: 420 },
  ],
};


// Data for vegetable gardening information
// Description of each vegetable is taken from chatgpt
const VEGETABLEGARDENINGINFO = [
  {
    id: 1,
    name: "Tomatoes",
    description:
      "Tomatoes are easy to grow in containers or small garden beds. They require full sun and regular watering. You can start with tomato seedlings or seeds.",
    image: "/images/gtomato.png",
  },
  {
    id: 2,
    name: "Lettuce",
    description:
      "Lettuce is a cool-season crop that can be grown in small spaces. It prefers partial shade and well-drained soil. You can harvest lettuce leaves as they grow for continuous supply.",
    image: "/images/lettuce.png",
  },
  {
    id: 3,
    name: "Radishes",
    description:
      "Radishes are fast-growing vegetables perfect for beginners. They can be grown in pots or directly in the ground. Radishes prefer cooler weather and consistent moisture.",
    image: "/images/raddish.png",
  },
  {
    id: 4,
    name: "Cucumbers",
    description:
      "Cucumbers are a great choice for backyard gardens. They prefer warm weather and plenty of water. You can train them to grow up a trellis to save space.",
    image: "/images/cucumber.png",
  },
  {
    id: 5,
    name: "Peppers",
    description:
      "Peppers are easy to grow and come in a variety of colors and flavors. They require full sun and well-drained soil. You can start with pepper seedlings or seeds.",
    image: "/images/pepper.png",
  },
  {
    id: 6,
    name: "Carrots",
    description:
      "Carrots are a classic backyard vegetable. They prefer loose, well-drained soil. You can sow carrot seeds directly in the ground in the spring or fall.",
    image: "/images/gcarrot.png",
  },
];

export { MEALS, ACTIVITYFACTORS, GOALFACTORS,  VEGETABLEGARDENINGINFO };
